# Site settings
title: Choi's blog
# description: 
# # baseurl: "/particle" # the subpath of your site, e.g. /blog
# # url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# # User settings
# username: Choi Sanghyeon
# user_description: 
# user_title: SW Developer
# email: csh1063@gmail.com
# github_username:  csh1063

# # Google-analytics
# google-analytics:
#   id: ""

# exclude: ['package.json', 'src' , 'node_modules']
# theme: jekyll-theme-so-simple

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: clean-blog