# Site settings
title:             Choi's blog
email:             csh1063@gmail.com
description:       
author:            Choi
baseurl:           "/blog"
url:               "https://csh1063.github.io"

# Social Profiles
twitter_username:  
github_username:   csh1063
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: jekyll-theme-awesome
